export const REQUEST_SUMMONER = 'REQUEST_SUMMONER';
export const RECEIVE_SUMMONER = 'RECEIVE_SUMMONER';
export const CHANGE_SEARCH_SUMMONER_NAME = 'CHANGE_SEARCH_SUMMONER_NAME';

export const RECEIVE_RECENT_GAMES = 'RECEIVE_RECENT_GAMES';
export const CLEAR_RECENT_GAMES = 'CLEAR_RECENT_GAMES';
export const RECEIVE_CHAMPION = 'RECEIVE_CHAMPION';
export const SELECT_GAME = 'SELECT_GAME';

export const RECEIVE_GAME_DETAIL = 'RECEIVE_GAME_DETAIL';
export const CLEAR_GAME_DETAIL = 'CLEAR_GAME_DETAIL';

export const RECEIVE_PARTICIPANT_CHAMPION = 'RECEIVE_PARTICIPANT_CHAMPION';