export const REQUEST_SUMMONER = 'REQUEST_SUMMONER';
export const RECEIVE_SUMMONER = 'RECEIVE_SUMMONER';
export const CHANGE_SUMMONER_NAME = 'CHANGE_SUMMONER_NAME';

export const RECEIVE_RECENT_GAMES = 'RECEIVE_RECENT_GAMES';
export const CLEAR_RECENT_GAMES = 'CLEAR_RECENT_GAMES';
export const RECEIVE_GAME_IMAGE = 'RECEIVE_GAME_IMAGE';
